
import React from 'react';
import Card from '../ui/Card';
import Button from '../ui/Button';

const ReportsPage: React.FC = () => {
  const handleOpenReport = (reportName: string) => {
    alert(`In a real application with a local server, this would open '${reportName}'. In this web demo, direct file access is not possible for security reasons.`);
  };

  return (
    <div className="animate-fade-in space-y-6">
      <h1 className="text-4xl font-bold text-white">Generated Reports</h1>
      <p className="text-lg text-slate-400">
        Access the data profiling and prediction reports generated by the pipeline.
      </p>
      
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <Card title="Data Profiling Report">
          <p className="text-slate-300 mb-4">
            A comprehensive HTML report generated by ydata-profiling, providing deep insights into the raw dataset. It includes statistics, distributions, correlations, and missing value analysis.
          </p>
          <Button onClick={() => handleOpenReport('profiling_report.html')}>
            View Profiling Report
          </Button>
        </Card>

        <Card title="Churn Predictions Report">
          <p className="text-slate-300 mb-4">
            A CSV file containing the latest churn predictions. This report includes customer IDs, their predicted churn status ('Yes' or 'No'), and the associated churn probability.
          </p>
          <Button onClick={() => handleOpenReport('churn_predictions.csv')}>
            View Predictions CSV
          </Button>
        </Card>
      </div>

       <div className="mt-6 p-4 bg-sky-900/50 border border-sky-700 rounded-lg text-sky-200">
        <h3 className="font-semibold">Note on Report Viewing</h3>
        <p className="text-sm mt-1">
          This is a frontend-only simulation. The buttons above demonstrate where you would access reports. Opening local files directly from a web browser is restricted for security. To view the actual reports, you would need to run the original Python project on your local machine.
        </p>
      </div>
    </div>
  );
};

export default ReportsPage;
